### ISSUE TITLE
node_processor.rb line 103 undefined method `sym?`

### ISSUE THREAD

**Issue by sclarson** [robotdana/leftovers#21]
Ran into the following in a build pipeline:

```
bundler: failed to load command: leftovers (/home/runner/work/myproject/myproject/vendor/bundle/ruby/3.1.0/bin/leftovers)
/home/runner/work/myproject/myproject/vendor/bundle/ruby/3.1.0/gems/leftovers-0.11.2/lib/leftovers/file_collector/node_processor.rb:103:in `on_block_pass': undefined method `sym?' for nil:NilClass (NoMethodError)
	from /home/runner/work/myproject/myproject/vendor/bundle/ruby/3.1.0/gems/ast-2.4.2/lib/ast/processor/mixin.rb:259:in `process'
	from /home/runner/work/myproject/myproject/vendor/bundle/ruby/3.1.0/gems/ast-2.4.2/lib/ast/processor/mixin.rb:276:in `block in process_all'
	from /home/runner/work/myproject/myproject/vendor/bundle/ruby/3.1.0/gems/ast-2.4.2/lib/ast/processor/mixin.rb:275:in `map'
	from /home/runner/work/myproject/myproject/vendor/bundle/ruby/3.1.0/gems/ast-2.4.2/lib/ast/processor/mixin.rb:275:in `process_all'
	from /home/runner/work/myproject/myproject/vendor/bundle/ruby/3.1.0/gems/parser-3.1.2.1/lib/parser/ast/processor.rb:181:in `on_send'
```

**Comment by robotdana** [comment]
Thanks for raising this, it should be fixed with newly released 0.12.1. feel free to reopen this if it isn't.
